title:              ModelShare
email:              OMF.CWG@gmail.com; hello@kairoi.uk;
description:        A Project by the Certification Working Group
author:             Open Modeling Foundation
baseurl:            "/ModelShare"
url:                "https://Ismael-KG.github.io"

# Social Profiles
twitter_username:   
github_username:    openmodelingfoundation
facebook_username:  
instagram_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
